image: node:18

stages:
  - install
  - build
  - test
  - deploy

# Install dependencies
install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

# Build the NestJS app
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

# Run tests
test:
  stage: test
  script:
    - npm run test

# Deploy (adjust this to your needs)
deploy:
  stage: deploy
  script:
    - echo "Deploying the app..."
  only:
    - master
