stages:
  - build
  - test
  - deploy

# Example build job
build:
  stage: build
  script:
    - echo "Building the project..."
    - npm install

# Example test job
test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test

# Example deploy job
deploy:
  stage: deploy
  script:
    - echo "Deploying project..."
    - npm run deploy
  only:
    - master
